traPtitech/manifest

dev-ops-bot/config/config.yaml
traQ clientのdevops-botの権限を2人に渡したいです
お願いします
=> 2人をtraq-uiのoperatorsに追加

README.md, applications/application-set.yaml, backup/k3s-backup-cron-workflow.yaml, backup/k3s-backup-workflow-template.yaml, backup/ksops.yaml, backup/kustomization.yaml, backup/kustomize-config.yaml, backup/scripts/backup-k3s.sh, backup/secrets/backup-keys.yaml
https://docs.k3s.io/datastore/backup-restore
=> take k3s sqlite backup

.github/workflows/validate.yaml, argo/kustomization.yaml
Reverts traPtitech/manifest#233
=> Revert "fix(github-release): update argoproj/argo-workflows to v3.5.2"

monitor/victoria-metrics/config/prometheus.yml
ref: https://git.trap.jp/SysAd/Tasks/issues/268
=> Prometheusのstatus監視URLを変更 (hyakkiyagyoに対応)

ns-system/db/mariadb-stateful-set.yaml
Reverts traPtitech/manifest#393
=> Revert "feat(container): update image mariadb to v11.3.2"

dev-ops-bot/config/config.yaml
=> oribeさん消去漏れを解消

ns-system/db/mongo-stateful-set.yaml
This reverts commit bfe8fa342e38961cd53989a490f6a488d82f56fa.
=> Revert "fix(container): update image mongo to v7.0.12"

dev-ops-bot/config/config.yaml
=> ぷぐまにneoshowcaseリリース権を付与

dev-ops-bot/config/config.yaml
確認お願いします！
各リポジトリ、すべてリリースタグを打てば自動でビルドイメージが生成、pushされるようになっているのでリリースタグ機能だけで大丈夫です
=> tpfのリリースタグを打つ機能を追加

.github/workflows/validate.yaml, traefik/cluster-role.yaml, traefik/daemon-set.yaml, traefik/kustomization.yaml
This reverts commit 2c1ca8d60e2450ff43ca44d312aa65dfbd164423.
=> Revert "feat(container): update image traefik to v3.1.0 (#540)"

dev-ops-bot/config/config.yaml
=> feat: traQ-UIのdeployとreleaseにreiを追加

check.sh
All directories should be buildable by kustomize
=> chores: fix check script

monitor/victoria-metrics/config/prometheus.yml
認証方法をportal pipelineを使ったものに戻したので
=> Gitea metrics の target をもとに戻す

monitor/victoria-metrics/config/prometheus.yml
grafana で表示される ping 値の一覧に tpf 関連を追加しました
ご確認をお願いします
=> traPortfolio への ping チェックを有効化

dev-ops-bot/config/config.yaml
=> ChangedMembers

ns-system/config/ns.yaml, ns-system/kustomization.yaml, preview-ns/staging-deployment.yaml
Reverts traPtitech/manifest#615
=> Revert "feat(container): update neoshowcase group (minor)"

harbor/values.yaml
=> harbor: maxJobWorkersを5に下げる

.github/renovate.json5, ns-system/kustomization.yaml
Temporarily revert ns-dashboard to v1.7.2.
Revert this PR once the issue with v1.7.3 is resolved.
=> fix: Temporarily revert ns-dashboard to v1.7.2

.github/renovate.json5, ns-system/kustomization.yaml
This reverts commit c22875b6ebb20115af61731527da370416731260.
=> Revert "temporarily revert ns-dashboard to 1.7.2 (#688)"

crowi/es-statefulset.yaml, gitea/act-runner/act-runner.yaml, gitea/act-runner/gitea-act-runner.yaml, ns-system/components/builder-deployment.yaml, traq/es-statefulset.yaml
=> e505にあるpodを退避

crowi/es-statefulset.yaml, gitea/act-runner/act-runner.yaml, gitea/act-runner/gitea-act-runner.yaml, ns-system/components/builder-deployment.yaml, traq/es-statefulset.yaml
=> Revert "e505にあるpodを退避 (#695)"

gitea/act-runner/gitea-act-runner.yaml
=> act_runnerの移動テスト

crowi/es-statefulset.yaml, gitea/act-runner/act-runner.yaml, gitea/act-runner/gitea-act-runner.yaml, ns-system/components/builder-deployment.yaml, traq/es-statefulset.yaml
[これ](https://github.com/traPtitech/manifest/pull/699)で移動したPodを戻す
=> 移動したPodを戻す

dev-ops-bot/config/config.yaml
=> add Pugma to traQ command list in config.yaml

litellm/config/config.yaml
=> gpt-4o-miniを追加

portal-dev/backend/ingress-route.yaml, portal-dev/frontend/ingress-route.yaml, traq-dev/backend/ingress-route.yaml, traq-dev/frontend/ingress-route.yaml
This reverts commit 458bd0879f12bcb49b6d9fc8e39d7b325c681126.
=> Revert "🔥 必要ないtls設定を削除 (#740)"

portal-dev/backend/ingress-route.yaml, portal-dev/frontend/ingress-route.yaml, portal-dev/frontend/service.yaml
Reverts traPtitech/manifest#759
=> Revert "Serviceのportを80にしてみる"

cert-manager/dns-cluster-issuer.yaml, cert-manager/kustomization.yaml, cert-manager/staging-cluster-issuer.yaml, portal-dev/certificate.yaml, traq-dev/certificate.yaml
- ✨ dnsのみのissuerを追加し、stagingを戻した
- 🐛 issuerをdnsに変更
=> issuerの設定を変更

cert-manager/cluster-issuer.yaml
http01 solver が上手く動いていないため (その根本的な原因は不明)
=> cluster-issuer から http01 solver を削除

portal-dev/frontend/deployment.yaml
https://github.com/traPtitech/portal-UI/releases/tag/v2.14.4
=> portal のフロントエンドのステージングのハッシュを更新

portal/frontend/deployment.yaml
https://github.com/traPtitech/portal-UI/releases/tag/v2.14.4
=> Portal のフロントエンドの本番デプロイ

.github/renovate/auto-merge.json5, .github/renovate/pin-digests.json5, portal/frontend/deployment.yaml
想定しているバージョニング
- production
- backend: オートマージ無効
- frontend: オートマージ無効
- pipeline: オートマージ無効
- staging
- backend: オートマージ有効
- frontend: オートマージ有効
=> Portalのバージョニングを調整

ns-system/components/builder-deployment.yaml, ns-system/components/controller-stateful-set.yaml, ns-system/components/dashboard-deployment.yaml, ns-system/components/gateway-deployment.yaml, ns-system/components/gitea-integration-stateful-set.yaml, ns-system/components/sablier-deployment.yaml, ns-system/components/ssgen-stateful-set.yaml, ns-system/db/adminer-deployment.yaml, ns-system/db/mariadb-stateful-set.yaml, ns-system/db/mongo-stateful-set.yaml
=> NeoShowcaseをストップ

traq-dev/backend/deployment.yaml, traq-dev/frontend/deployment.yaml, traq-dev/widget/deployment.yaml
=> traq-devをc1-203に戻してみる

.github/workflows/diff.yaml
https://github.com/homeport/dyff/pull/409 がマージ&リリースされてたので
=> Use upstream dyff

preview-knoq/application-set.yaml, preview-knoq/certificate.yaml, preview-knoq/kustomization.yaml, preview-knoq/middleware-sablier.yaml, preview-knoq/staging-deployment.yaml, preview-knoq/staging-ingress-route.yaml, preview-knoq/staging-service.yaml, preview-knoq/template/Chart.yaml, preview-knoq/template/templates/ingress-route.yaml, preview-knoq/template/templates/middleware-sablier.yaml, preview-knoq/template/templates/ui-deployment.yaml, preview-knoq/template/templates/ui-service.yaml, preview-knoq/template/values.yaml, traefik/config/static-file-provider.yaml
=> preview knoQ

portal-dev/backend/deployment.yaml, portal-dev/frontend/deployment.yaml, traq-dev/backend/deployment.yaml, traq-dev/frontend/deployment.yaml, traq-dev/widget/deployment.yaml
traQ-devとportal-devのdeployment.yamlから不要部分を削除
ラベル名を生成されたものから変更
part of #822
=> traq-dev / portal-dev の labels をシンプルにリファクタリング

ns-system/components/builder-deployment.yaml
=> increase ns-builder's memory limit

edit-secret.sh
edit-secret.sh で編集する際に使う editor を `EDITOR` 環境変数で指定できるようにした
=> edit-secret.sh で編集する際に使う editor を指定できるように

traefik/daemon-set.yaml
Reverts traPtitech/manifest#867
=> Revert "feat(container): update image traefik to v3.4.0"

monitor/victoria-metrics/secrets/tailscale-credential.yaml, monitor/victoria-metrics/stateful-set.yaml
公式の example に寄せた
https://github.com/tailscale/tailscale/blob/main/docs/k8s/sidecar.yaml
=> Tailscale Sidecar の書き方を更新

ns-system/backup/scripts/backup-mariadb.sh
=> ns-mariadbのバックアップ時にログを出力する

ns-system/backup/scripts/backup-mariadb.sh
Reverts traPtitech/manifest#885
#886 で調査終了
=> Revert "ns-mariadbのバックアップ時にログを出力する"

argocd/patches/argocd-cm.yaml
system-upgrade-controllerのCRDが無限にOutOfSyncになってしまう問題の対応
=> ArgoCDのOutOfSyncを回避する

minio-dev/volume-storage.yaml
元から予定されていた25GBに
https://q.trap.jp/messages/0196944f-bd72-7c86-ba8c-b6c617c26451
=> s3-devのVolumeのsizeを増やす

monitor/victoria-metrics/config/prometheus.yml, sakura-monitor/victoria-metrics/config/prometheus.yml
=> llm-proxy.trap.jpとs3-dev.trap.jpのURLをVictoriaMetricsの設定に追加

traq-dev/frontend/deployment-patch.yaml, traq/frontend/deployment.yaml
https://github.com/traPtitech/traQ_S-UI/pull/4643 がリリースされるまではマージしても効力がないです
=> feat: traQ フロントエンドに New  Relic を導入した

ns-system/components/builder-deployment.yaml, ns-system/config/buildkitd.toml, ns-system/kustomization.yaml
=> configure registry mirror

litellm/config/config.yaml
https://github.com/traPtitech/BOT_GPT/pull/40 　の変更に対応するために，gpt-4.1を使用するための設定を追加しました
https://docs.litellm.ai/docs/providers/openai　を参考にしました
=> gpt-4.1を使用するための設定を追加する

ns-dev-system/components/controller-deployment.yaml, ns-dev-system/components/controller-stateful-set-patch.yaml, ns-dev-system/kustomization.yaml, ns-system/components/controller-cluster-role.yaml
- ns-controllerをDeploymentに
- endpoint slice関連の権限を付与
=> update ns-dev to 1.9.0

rucq-dev/backend-deployment-patch.yaml, rucq-dev/ksops.yaml, rucq-dev/secrets/traq-token.yaml, rucq/backend-deployment.yaml, rucq/ksops.yaml, rucq/secrets/traq-token.yaml
Readmeの手順に従ってsecretを追加し、必要そうなところを雰囲気で編集しました
=> rucQにbot用のtokenを追加

.github/workflows/renovate.yaml
=> fix:version

ns-system/kustomization.yaml
Reverts traPtitech/manifest#1090
=> Revert "update neoshowcase to 1.9.3"

ns-system/kustomization.yaml
Reverts traPtitech/manifest#1095
=> Reapply "update neoshowcase to 1.9.3"

ns-dev-system/components/controller-deployment-patch.yaml, ns-dev-system/kustomization.yaml, ns-system/components/controller-deployment.yaml, ns-system/kustomization.yaml
Reverts traPtitech/manifest#1094
=> Reapply "ns-controllerをDeploymentに変更"

argocd/patches/argocd-notifications-cm.yaml, preview-rucq-admin/kustomization.yaml, preview-rucq-admin/values.yaml, preview-rucq-ui/kustomization.yaml, preview-rucq-ui/values.yaml
`preview-rucq-ui`、`preview-rucq-admin`を追加
=> rucQにpreview appを追加

litellm/deployment.yaml
as titled
https://github.com/BerriAI/litellm/releases/tag/v1.75.5-stable
=> upgrade litellm

litellm/config/config.yaml
=> feat: add gpt-5 models

rucq-dev/secrets/traq-token.yaml
=> access tokenとverification tokenが逆になっていたのを修正
